//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manuf
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManafactuterEntities : DbContext
    {
        private static ManafactuterEntities _context;
        public ManafactuterEntities()
            : base("name=ManafactuterEntities")
        {
        }
        public static ManafactuterEntities GetContext()
        {
            if (_context == null)
                _context = new ManafactuterEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sale> sale { get; set; }
    }
}
