//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manuf
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int id { get; set; }
        public string name { get; set; }
        public int count { get; set; }
        public System.DateTime date_of_sale { get; set; }
        public System.TimeSpan time_of_sale { get; set; }
    }
}
